### ISSUE TITLE
Horizontal rule doesn't look good in the docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-horizontal-rule#2]
It's more narrow than the line under the heading. Also, it has a different thickness.

![image](https://user-images.githubusercontent.com/156149/64259133-cc9d1980-cf28-11e9-8eb1-3cc59e231c03.png)

**Comment by Reinmar** [comment]
We can use a different heading level for this demo, but the problem will still be somewhere there. 

I also think that this color or 2px thickness may not be working best with our docs and the editor as a whole. The editor has a 1px borders and we use a lighter grey for them too. I don't know whether this 2px border will actually ever look good.

**Comment by Reinmar** [comment]
cc @dkonopka

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
![image](https://user-images.githubusercontent.com/1099479/65312613-2d685b00-db93-11e9-85df-65d45da59726.png)


```css
.ck-content hr {
    border-color: hsl(0, 0%, 37%);
    border-width: 1px 0 0;
    border-style: solid;
    margin: 0;
    padding: 0;
}

.ck .ck-horizontal-rule {
    overflow: hidden;
    padding: 5px 0;
}
```
