### ISSUE TITLE
Horizontalrule.css needs some refactoring

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-horizontal-rule#8]
A twin to https://github.com/ckeditor/ckeditor5-page-break/issues/8.

It looks like styles in the file are content styles, so all we need is the `.ck-content` prefix. But this must be double-checked.

**Comment by oleq** [comment]
```css
// Let's make it .ck .ck-widget.ck-horizontal-rule
.ck .ck-horizontal-rule {
	/* Handle proper `<hr>` display next to elements with `float` property, e.g. side image case. */
	overflow: hidden; // -> this should stay here
	padding: 5px 0; // -> this should go to Lark
}

// This stays here
.ck-content hr {
	border-width: 1px 0 0;
	border-style: solid;
	border-color: hsl(0, 0%, 37%);
	margin: 0;
}
```
